language: java

branches:
  only:
    - master
    - /^release.*$/ 

jdk:
  - oraclejdk8

before_script:
- echo "hello from slatekit"
- echo "$TRAVIS_BUILD_DIR"
- cd ./src/lib/kotlin/slatekit
- chmod +x gradlew
- chmod +x gradle/wrapper/gradle-wrapper.jar

script:
- ./gradlew build