version: '3'

services:
# MySql - docker compose up -d
  db:
    container_name: mysql-8
    image: mysql:8.0.35
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 12345qwert
      MYSQL_DATABASE: kiit
    ports:
      - '3306:3306'
    volumes:
      - db-volume:/var/lib/mysql
      - './install/db/mysql/3.x:/docker-entrypoint-initdb.d'

volumes:
  db-volume: