hugo new core/apis.md
hugo new core/app.md
hugo new core/cache.md
hugo new core/commands.md
hugo new core/cli.md
hugo new core/context.md
hugo new core/email.md
hugo new core/files.md
hugo new core/notifications.md
hugo new core/entities.md
hugo new core/orm.md
hugo new core/queues.md
hugo new core/server.md
hugo new core/sms.md
hugo new core/workers.mdexists
hugo new core/workers.md
hugo new core/results.md