/**
    This code is auto-generated by the Slate Kit Api Component.
    @author  : Slate Kit
    @about   : @{about}
    @desc    : @{description}
    @route   : @{route}
    @version : @{version}
    @software: Visit www.slatekit.com for more info
*/
package @{packageName}.client.api

import @{packageName}.client.core.*
import @{packageName}.client.dto.*

import java.util.Date;

class @{className}Api(client: HttpClient?) : ApiBase(client) {
	
    @{methods}
}