/**
    This code is auto-generated by the Slate Kit Api Component.
    @author  : Slate Kit
    @about   : @{about}
    @desc    : @{description}
    @route   : @{route}
    @version : @{version}
    @software: Visit www.slatekit.com for more info
*/
package @{packageName}.clientapis

import @{packageName}.clientapis.dtos.*
import slatekit.common.HttpRPC
import slatekit.http.ApiBase
import slatekit.http.converters.*
import slatekit.results.Outcome

import java.util.Date;

class @{className}Api(http: HttpRPC) : ApiBase(http) {

    constructor() : this(HttpRPC())

    @{methods}
}