/**
    This code is auto-generated by the Slate Kit Api Component.
    @author  : Slate Kit
    @about   : @{about}
    @desc    : @{description}
    @route   : @{route}
    @version : @{version}
    @software: Visit www.slatekit.com for more info
*/
package @{packageName}.client.api;

import @{packageName}.client.core.*;
import @{packageName}.client.dto.*;

import java.util.HashMap;
import java.util.List;
import java.util.Date;
import java.util.Map;

public class @{className}Api extends ApiBase {

    public @{className}Api(){
    }


    public @{className}Api(HttpClient client){
        super(client);
    }
	
    @{methods}
}