/**
    This code is auto-generated by the Slate Kit Api Component.
    @author  : Slate Kit
    @version : @{version}
    @software: Visit www.slatekit.com for more info
*/
package @{packageName}.client.dto;

import java.util.Date;

/**
 * Auto-generated simple DTO ( Data Transfer Object ) for the api.
 * Used only for transferring info to/from server.
 */
public class @{className} {
    @{properties}
}