# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

# on:
#   release:
#     types: [created]

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: ''
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SLATEKIT_PROJECT_MODE: binary
        SLATEKIT_INSTALL_ACTOR: ${{ secrets.SLATEKIT_INSTALL_ACTOR }}
        SLATEKIT_INSTALL_TOKEN: ${{ secrets.SLATEKIT_INSTALL_TOKEN }}
        SLATEKIT_BINTRAY_ACTOR: ${{ secrets.SLATEKIT_BINTRAY_ACTOR }}
        SLATEKIT_BINTRAY_TOKEN: ${{ secrets.SLATEKIT_BINTRAY_TOKEN }}
        SLATEKIT_PUBLISH_ACTOR: ${{ github.actor }}
        SLATEKIT_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build SlateKit.Result with Gradle
      working-directory: src/lib/kotlin/slatekit-result
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.Actors with Gradle
      working-directory: src/lib/kotlin/slatekit-actors
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.Common with Gradle
      working-directory: src/lib/kotlin/slatekit-common
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.Context with Gradle
      working-directory: src/lib/kotlin/slatekit-context
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.tracking with Gradle
      working-directory: src/lib/kotlin/slatekit-tracking
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.policy with Gradle
      working-directory: src/lib/kotlin/slatekit-policy
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.meta with Gradle
      working-directory: src/lib/kotlin/slatekit-meta
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.serialization with Gradle
      working-directory: src/lib/kotlin/slatekit-serialization
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.http with Gradle
      working-directory: src/lib/kotlin/slatekit-http
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.core with Gradle
      working-directory: src/lib/kotlin/slatekit-core
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.app with Gradle
      working-directory: src/lib/kotlin/slatekit-app
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.cli with Gradle
      working-directory: src/lib/kotlin/slatekit-cli
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.jobs with Gradle
      working-directory: src/lib/kotlin/slatekit-jobs
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.apis with Gradle
      working-directory: src/lib/kotlin/slatekit-apis
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.cache with Gradle
      working-directory: src/lib/kotlin/slatekit-cache
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.db with Gradle
      working-directory: src/lib/kotlin/slatekit-db
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.notifications with Gradle
      working-directory: src/lib/kotlin/slatekit-notifications
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.query with Gradle
      working-directory: src/lib/kotlin/slatekit-query
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.data with Gradle
      working-directory: src/lib/kotlin/slatekit-data
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.entities with Gradle
      working-directory: src/lib/kotlin/slatekit-entities
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.migrations with Gradle
      working-directory: src/lib/kotlin/slatekit-migrations
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    # Providers
    - name: Build Slate Kit Providers - AWS with Gradle
      working-directory: src/ext/kotlin/slatekit-providers-aws
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build Slate Kit Providers - DataDog with Gradle
      working-directory: src/ext/kotlin/slatekit-providers-datadog
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build Slate Kit Providers - Logback with Gradle
      working-directory: src/ext/kotlin/slatekit-providers-logback
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    # Connectors
    - name: Build Slate Kit Connectors - AWS with Gradle
      working-directory: src/ext/kotlin/slatekit-connectors-cli
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build Slate Kit Connectors - DataDog with Gradle
      working-directory: src/ext/kotlin/slatekit-connectors-entities
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build Slate Kit Connectors - Logback with Gradle
      working-directory: src/ext/kotlin/slatekit-connectors-jobs
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    # Integration
    - name: Build SlateKit.integration with Gradle
      working-directory: src/lib/kotlin/slatekit-integration
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.server with Gradle
      working-directory: src/lib/kotlin/slatekit-server
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

    - name: Build SlateKit.generator with Gradle
      working-directory: src/lib/kotlin/slatekit-generator
      run: gradle clean build publish
    - name: Sleep for 30 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '30s'

