# This workflow will build main kiit project and run unit-tests for CI ( continuous integration )
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: CI Test

on: 
  push:
   branches:
     - fea/*
     - fix/*
     - hot/*
     - rel/*       
  release:
   types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        KIIT_PROJECT_MODE: binary
        KIIT_INSTALL_ACTOR: ${{ secrets.KIIT_INSTALL_ACTOR }}
        KIIT_INSTALL_TOKEN: ${{ secrets.KIIT_INSTALL_TOKEN }}
        KIIT_PUBLISH_ACTOR: ${{ github.actor }}
        KIIT_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.7.1

# ====================================================
# Common
# ====================================================
    - name: Build Kiit which includes tests
      working-directory: src/lib/kotlin/kiit
      run: gradle clean build
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'


