# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

# on:
#   release:
#     types: [created]

on: 
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: false
        default: ''
  #push:
  #  branches:
  #    - feature/*
  #    - release/*
  #    - hotfix/*       
  #release:
  #  types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        KIIT_PROJECT_MODE: binary
        KIIT_INSTALL_ACTOR: ${{ secrets.KIIT_INSTALL_ACTOR }}
        KIIT_INSTALL_TOKEN: ${{ secrets.KIIT_INSTALL_TOKEN }}
        KIIT_PUBLISH_ACTOR: ${{ github.actor }}
        KIIT_PUBLISH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 6.7.1

# ====================================================
# Common
# ====================================================
    - name: Build Result with Gradle
      working-directory: src/common/result
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build Actors with Gradle
      working-directory: src/common/actors
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build Common with Gradle
      working-directory: src/common/common
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build Utils with Gradle
      working-directory: src/common/utils
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build Requests with Gradle
      working-directory: src/common/requests
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build Context with Gradle
      working-directory: src/common/context
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build http with Gradle
      working-directory: src/common/http
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

# ====================================================
# Internal
# ====================================================
    - name: Build Telemetry with Gradle
      working-directory: src/infra/telemetry
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build policy with Gradle
      working-directory: src/internal/policy
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build meta with Gradle
      working-directory: src/internal/meta
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build serialization with Gradle
      working-directory: src/internal/serialization
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

# ====================================================
# Runnable services
# ====================================================
    - name: Build app with Gradle
      working-directory: src/services/app
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build cli with Gradle
      working-directory: src/services/cli
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build jobs with Gradle
      working-directory: src/services/jobs
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build apis with Gradle
      working-directory: src/services/apis
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build server with Gradle
      working-directory: src/services/server
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

# ====================================================
# Infrastructure
# ====================================================
    - name: Build core with Gradle
      working-directory: src/infra/core
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build cache with Gradle
      working-directory: src/infra/cache
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build db with Gradle
      working-directory: src/infra/db
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build notifications with Gradle
      working-directory: src/infra/comms
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

# ====================================================
# Data
# ====================================================
    - name: Build query with Gradle
      working-directory: src/data/query
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build data with Gradle
      working-directory: src/data/data
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build entities with Gradle
      working-directory: src/data/entities
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

    - name: Build migrations with Gradle
      working-directory: src/data/migrations
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with: 
        time: '25s'

# ====================================================
# Providers
# ====================================================
    - name: Build Providers - AWS with Gradle
      working-directory: src/providers/providers-aws
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

    - name: Build Providers - DataDog with Gradle
      working-directory: src/providers/providers-datadog
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

    - name: Build Providers - Logback with Gradle
      working-directory: src/providers/providers-logback
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

    - name: Build Providers - Kafka
      working-directory: src/providers/providers-kafka
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

# ====================================================
# Connectors
# ====================================================
    - name: Build Connectors - AWS with Gradle
      working-directory: src/connectors/connectors-cli
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

    - name: Build Connectors - DataDog with Gradle
      working-directory: src/connectors/connectors-entities
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

    - name: Build Connectors - Logback with Gradle
      working-directory: src/connectors/connectors-jobs
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

# ====================================================
# Integration
# ====================================================
    - name: Build integration with Gradle
      working-directory: src/lib/kotlin/integration
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'

    - name: Build generator with Gradle
      working-directory: src/lib/kotlin/generator
      run: gradle clean build publish
    - name: Sleep for 20 seconds
      uses: whatnick/wait-action@master
      with:
        time: '25s'
