# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#publishing-using-gradle

name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    # ====================================================
    # Slate Kit-Result
    - name: Build Result with Gradle
      working-directory: src/lib/kotlin/slatekit-result
      run: gradle build

    - name: Publish Result to GitHub Packages
      working-directory: src/lib/kotlin/slatekit-result
      run: gradle publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # ====================================================

    # ====================================================
    # Slate Kit-Common
    - name: Build Commons with Gradle
      working-directory: src/lib/kotlin/slatekit-common
      run: gradle build

    - name: Publish Common to GitHub Packages
      working-directory: src/lib/kotlin/slatekit-common
      run: gradle publish
      env:
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # ====================================================